export const DESTINATIONS = [
  {
    id: "bcn",
    city: "Barcelona",
    country: "Espanya",
    tag: "Popular",
    tagColor: "blue",
    from: 320,
    cats: ["city", "beach", "culture"],
    img: "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=600&q=80&fit=crop&crop=center",
    temp: "24°",
    hours: "2h vol",
  },
  {
    id: "lis",
    city: "Lisboa",
    country: "Portugal",
    tag: "Recomanat",
    tagColor: "green",
    from: 480,
    cats: ["city", "culture", "beach"],
    img: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=600&q=80&fit=crop&crop=center",
    temp: "22°",
    hours: "2.5h vol",
  },
  {
    id: "rom",
    city: "Roma",
    country: "Itàlia",
    tag: "Popular",
    tagColor: "blue",
    from: 720,
    cats: ["city", "culture"],
    img: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=600&q=80&fit=crop&crop=center",
    temp: "26°",
    hours: "2h vol",
  },
  {
    id: "par",
    city: "París",
    country: "França",
    tag: "Premium",
    tagColor: "gold",
    from: 890,
    cats: ["city", "culture"],
    img: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600&q=80&fit=crop&crop=center",
    temp: "19°",
    hours: "1.5h vol",
  },
  {
    id: "ist",
    city: "Istanbul",
    country: "Turquia",
    tag: "Recomanat",
    tagColor: "green",
    from: 640,
    cats: ["city", "culture", "adventure"],
    img: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=600&q=80&fit=crop&crop=center",
    temp: "28°",
    hours: "3h vol",
  },
  {
    id: "cph",
    city: "Copenhaguen",
    country: "Dinamarca",
    tag: "Premium",
    tagColor: "gold",
    from: 1120,
    cats: ["city", "culture"],
    img: "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=600&q=80&fit=crop&crop=center",
    temp: "15°",
    hours: "2.5h vol",
  },
  {
    id: "ath",
    city: "Atenes",
    country: "Grècia",
    tag: "Popular",
    tagColor: "blue",
    from: 690,
    cats: ["city", "culture", "beach"],
    img: "https://images.unsplash.com/photo-1555993539-1732b0258235?w=600&q=80&fit=crop&crop=center",
    temp: "30°",
    hours: "3h vol",
  },
  {
    id: "mar",
    city: "Marràqueix",
    country: "Marroc",
    tag: "Recomanat",
    tagColor: "green",
    from: 540,
    cats: ["culture", "adventure"],
    img: "https://images.unsplash.com/photo-1597212618440-806262de4f6b?w=600&q=80&fit=crop&crop=center",
    temp: "32°",
    hours: "2.5h vol",
  },
  {
    id: "tok",
    city: "Tòquio",
    country: "Japó",
    tag: "Premium",
    tagColor: "gold",
    from: 1850,
    cats: ["city", "culture", "adventure"],
    img: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600&q=80&fit=crop&crop=center",
    temp: "22°",
    hours: "13h vol",
  },
  {
    id: "rey",
    city: "Reykjavík",
    country: "Islàndia",
    tag: "Premium",
    tagColor: "gold",
    from: 1280,
    cats: ["adventure", "nature"],
    img: "https://images.unsplash.com/photo-1486931643691-cb91d4f81e76?w=600&q=80&fit=crop&crop=center",
    temp: "8°",
    hours: "3h vol",
  },
  {
    id: "dub",
    city: "Dubai",
    country: "EAU",
    tag: "Premium",
    tagColor: "gold",
    from: 1450,
    cats: ["city", "beach", "adventure"],
    img: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600&q=80&fit=crop&crop=center",
    temp: "38°",
    hours: "6h vol",
  },
  {
    id: "mia",
    city: "Miami",
    country: "EUA",
    tag: "Popular",
    tagColor: "blue",
    from: 980,
    cats: ["beach", "city"],
    img: "https://images.unsplash.com/photo-1506966953602-c20cc11f75e3?w=600&q=80&fit=crop&crop=center",
    temp: "33°",
    hours: "10h vol",
  },
];

export type Destination = (typeof DESTINATIONS)[0];

export const TRANSPORT = [
  { id: "plane", label: "Avió", sub: "Més ràpid", color: "coral" },
  { id: "train", label: "Tren", sub: "Sostenible", color: "blue" },
  { id: "bus", label: "Bus / Ferri", sub: "Econòmic", color: "green" },
  { id: "car", label: "Cotxe propi", sub: "Flexible", color: "gold" },
];

export type Transport = (typeof TRANSPORT)[0];

export function budgetZone(v: number) {
  if (v < 600) return { label: "Econòmic", sub: "Escapades curtes a Europa" };
  if (v < 1500) return { label: "Equilibrat", sub: "5-7 dies a Europa" };
  if (v < 3000) return { label: "Confortable", sub: "Intercontinental" };
  return { label: "Premium", sub: "Sense compromís" };
}

export function monthAbbr(d: Date) {
  return [
    "gen",
    "feb",
    "mar",
    "abr",
    "mai",
    "jun",
    "jul",
    "ago",
    "set",
    "oct",
    "nov",
    "des",
  ][d.getMonth()];
}

export const DEST_CATEGORIES = [
  { id: "all", label: "Tots", icon: "all" },
  { id: "city", label: "Ciutat", icon: "city" },
  { id: "beach", label: "Platja", icon: "beach" },
  { id: "culture", label: "Cultura", icon: "culture" },
  { id: "adventure", label: "Aventura", icon: "adventure" },
  { id: "nature", label: "Natura", icon: "nature" },
];

export const SAMPLE_TRIPS = [
  {
    id: "t1",
    destId: "lis",
    city: "Lisboa",
    country: "Portugal",
    start: "12 mar",
    end: "18 mar",
    days: 6,
    people: 2,
    total: 1148,
    status: "upcoming" as const,
    favorite: true,
    img: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=80&fit=crop&crop=center",
  },
  {
    id: "t2",
    destId: "rom",
    city: "Roma",
    country: "Itàlia",
    start: "04 oct",
    end: "09 oct",
    days: 5,
    people: 2,
    total: 1340,
    status: "past" as const,
    favorite: false,
    img: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&q=80&fit=crop&crop=center",
  },
  {
    id: "t3",
    destId: "cph",
    city: "Copenhaguen",
    country: "Dinamarca",
    start: "22 jul",
    end: "27 jul",
    days: 5,
    people: 2,
    total: 1890,
    status: "past" as const,
    favorite: false,
    img: "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800&q=80&fit=crop&crop=center",
  },
];

export type Trip = (typeof SAMPLE_TRIPS)[0];
