-- AlterTable
ALTER TABLE "Trip" ADD COLUMN "country" TEXT;
ALTER TABLE "Trip" ADD COLUMN "imageUrl" TEXT;
ALTER TABLE "Trip" ADD COLUMN "people" INTEGER NOT NULL DEFAULT 2;
ALTER TABLE "Trip" ADD COLUMN "searchId" TEXT;
ALTER TABLE "Trip" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AddForeignKey
ALTER TABLE "Trip" ADD CONSTRAINT "Trip_searchId_fkey" FOREIGN KEY ("searchId") REFERENCES "TravelSearch"("id") ON DELETE SET NULL ON UPDATE CASCADE;
